// --------------------------------------------------------------
// -                        Test Scripts                        -
// --------------------------------------------------------------
// These scripts are meant for regression test purposes.

//diabro-npc/test/infinite_warp.txt
//diabro-npc/test/OnInterInit.txt
//diabro-npc/test/npc_test_checkweight.txt
