// --------------------------------------------------------------
// -                      Monster  Scripts                      -
// --------------------------------------------------------------

//diabro-npc/mobs/jail.txt
//diabro-npc/mobs/pvp.txt
//diabro-npc/mobs/towns.txt
