// --------------------------------------------------------------
// -                         Guild Wars                         -
// --------------------------------------------------------------
//diabro-
// ----------------------- War of Emperium ----------------------
// - Guild WoE time settings
//diabro-npc/guild/agit_controller.txt 
// - Guild NPC Template file
//diabro-npc/guild/agit_main.txt
// - Al De Baran
//diabro-npc/guild/aldeg_cas01.txt
//diabro-npc/guild/aldeg_cas02.txt
//diabro-npc/guild/aldeg_cas03.txt
//diabro-npc/guild/aldeg_cas04.txt
//diabro-npc/guild/aldeg_cas05.txt
// - Geffen
//diabro-npc/guild/gefg_cas01.txt
//diabro-npc/guild/gefg_cas02.txt
//diabro-npc/guild/gefg_cas03.txt
//diabro-npc/guild/gefg_cas04.txt
//diabro-npc/guild/gefg_cas05.txt
// - Payon
//diabro-npc/guild/payg_cas01.txt
//diabro-npc/guild/payg_cas02.txt
//diabro-npc/guild/payg_cas03.txt
//diabro-npc/guild/payg_cas04.txt
//diabro-npc/guild/payg_cas05.txt
// - Prontera
//diabro-npc/guild/prtg_cas01.txt
//diabro-npc/guild/prtg_cas02.txt
//diabro-npc/guild/prtg_cas03.txt
//diabro-npc/guild/prtg_cas04.txt
//diabro-npc/guild/prtg_cas05.txt
// - Treasure Room Protection
////diabro-npc/guild/trs_rp.txt

// --------------- War of Emperium Second Edition ---------------
// - WoE SE time settings
//diabro-npc/guild2/agit_start_se.txt
// - Guild NPC Template file
//diabro-npc/guild2/agit_main_se.txt
// - Town Flags
//diabro-npc/guild2/guild_flags.txt
// - Arunafeltz
//diabro-npc/guild2/arug_cas01.txt
//diabro-npc/guild2/arug_cas02.txt
//diabro-npc/guild2/arug_cas03.txt
//diabro-npc/guild2/arug_cas04.txt
//diabro-npc/guild2/arug_cas05.txt
// - Schwarzwald
//diabro-npc/guild2/schg_cas01.txt
//diabro-npc/guild2/schg_cas02.txt
//diabro-npc/guild2/schg_cas03.txt
//diabro-npc/guild2/schg_cas04.txt
//diabro-npc/guild2/schg_cas05.txt
