// --------------------------------------------------------------
// -                        Warp Scripts                        -
// --------------------------------------------------------------

// --------------------------- Cities ---------------------------
//diabro-npc/warps/cities/alberta.txt
//diabro-npc/warps/cities/aldebaran.txt
//diabro-npc/warps/cities/amatsu.txt
//diabro-npc/warps/cities/ayothaya.txt
//diabro-npc/warps/cities/brasilis.txt
//diabro-npc/warps/cities/comodo.txt
//diabro-npc/warps/cities/einbech.txt
//diabro-npc/warps/cities/einbroch.txt
//diabro-npc/warps/cities/geffen.txt
//diabro-npc/warps/cities/gonryun.txt
//diabro-npc/warps/cities/hugel.txt
//diabro-npc/warps/cities/lighthalzen.txt
//diabro-npc/warps/cities/louyang.txt
//diabro-npc/warps/cities/lutie.txt
//diabro-npc/warps/cities/manuk.txt
//diabro-npc/warps/cities/mid_camp.txt
//diabro-npc/warps/cities/morroc.txt
//diabro-npc/warps/cities/moscovia.txt
//diabro-npc/warps/cities/nameless.txt
//diabro-npc/warps/cities/niflheim.txt
//diabro-npc/warps/cities/payon.txt
//diabro-npc/warps/cities/prontera.txt
//diabro-npc/warps/cities/splendide.txt
//diabro-npc/warps/cities/umbala.txt
//diabro-npc/warps/cities/veins.txt
//diabro-npc/warps/cities/yuno.txt

// -------------------------- Dungeons --------------------------
//diabro-npc/warps/dungeons/abbey.txt
//diabro-npc/warps/dungeons/abyss.txt
//diabro-npc/warps/dungeons/alde_dun.txt
//diabro-npc/warps/dungeons/ama_dun.txt
//diabro-npc/warps/dungeons/anthell.txt
//diabro-npc/warps/dungeons/ayo_dun.txt
//diabro-npc/warps/dungeons/beach_dun.txt
//diabro-npc/warps/dungeons/bra_dun.txt
//diabro-npc/warps/dungeons/c_tower.txt
//diabro-npc/warps/dungeons/ein_dun.txt
//diabro-npc/warps/dungeons/gef_dun.txt
//diabro-npc/warps/dungeons/gon_dun.txt
//diabro-npc/warps/dungeons/ice_dun.txt
//diabro-npc/warps/dungeons/in_sphinx.txt
//diabro-npc/warps/dungeons/iz_dun.txt
//diabro-npc/warps/dungeons/juperos.txt
//diabro-npc/warps/dungeons/kh_dun.txt
//diabro-npc/warps/dungeons/lhz_dun.txt
//diabro-npc/warps/dungeons/lou_dun.txt
//diabro-npc/warps/dungeons/mag_dun.txt
//diabro-npc/warps/dungeons/mjo_dun.txt
//diabro-npc/warps/dungeons/moc_pryd.txt
//diabro-npc/warps/dungeons/mosk_dun.txt
//diabro-npc/warps/dungeons/odin.txt
//diabro-npc/warps/dungeons/orcsdun.txt
//diabro-npc/warps/dungeons/pay_dun.txt
//diabro-npc/warps/dungeons/prt_maze.txt
//diabro-npc/warps/dungeons/ra_san.txt
//diabro-npc/warps/dungeons/tha_t.txt
//diabro-npc/warps/dungeons/thor_v.txt
//diabro-npc/warps/dungeons/treasure.txt
//diabro-npc/warps/dungeons/tur_dun.txt
//diabro-npc/warps/dungeons/um_dun.txt
//diabro-npc/warps/dungeons/xmas_dun.txt

// --------------------------- Fields ---------------------------
//diabro-npc/warps/fields/abyss_warper.txt
//diabro-npc/warps/fields/amatsu_fild.txt
//diabro-npc/warps/fields/bra_fild.txt
//diabro-npc/warps/fields/ein_fild.txt
//diabro-npc/warps/fields/gefenia.txt
//diabro-npc/warps/fields/glastheim.txt
//diabro-npc/warps/fields/jawaii.txt
//diabro-npc/warps/fields/lhalzen_fild.txt
//diabro-npc/warps/fields/lutie_fild.txt
//diabro-npc/warps/fields/man_fild.txt
//diabro-npc/warps/fields/mtmjolnir.txt
//diabro-npc/warps/fields/spl_fild.txt
//diabro-npc/warps/fields/umbala_fild.txt

// --------------------------- Others ---------------------------
//diabro-npc/warps/other/airplane.txt
//diabro-npc/warps/other/arena.txt
//diabro-npc/warps/other/god.txt
//diabro-npc/warps/other/jobquests.txt
//diabro-npc/warps/other/kiel.txt
//diabro-npc/warps/other/other.txt
//diabro-npc/warps/guildcastles.txt
//diabro-npc/warps/pvp.txt
