// --------------------------------------------------------------
// -                         Map  Flags                         -
// --------------------------------------------------------------
//diabro-npc/mapflag/nopvp.txt
//diabro-npc/mapflag/gvg.txt
//diabro-npc/mapflag/gvg_noparty.txt
//diabro-npc/mapflag/hidemobhpbar.txt
//diabro-npc/mapflag/jail.txt
//diabro-npc/mapflag/nightmare.txt
//diabro-npc/mapflag/nobranch.txt
//diabro-npc/mapflag/noicewall.txt
//diabro-npc/mapflag/nomemo.txt
//diabro-npc/mapflag/nopenalty.txt
//diabro-npc/mapflag/nosave.txt
//diabro-npc/mapflag/noteleport.txt
//diabro-npc/mapflag/noreturn.txt
//diabro-npc/mapflag/noskill.txt
//diabro-npc/mapflag/nowarp.txt
//diabro-npc/mapflag/nowarpto.txt
////diabro-npc/mapflag/partylock.txt
//diabro-npc/mapflag/pvp.txt
//diabro-npc/mapflag/pvp_noparty.txt
//diabro-npc/mapflag/pvp_noguild.txt
//diabro-npc/mapflag/night.txt
//diabro-npc/mapflag/reset.txt
//diabro-npc/mapflag/restricted.txt
//diabro-npc/mapflag/battleground.txt
//diabro-npc/mapflag/skill_damage.txt
//diabro-npc/mapflag/town.txt
//diabro-npc/mapflag/nocostume.txt
//diabro-npc/mapflag/skill_duration.txt
//diabro-npc/mapflag/nodynamicnpc.txt
